
[plugin-info]
SHORT_PLUGIN_NAME = 'alcatel'

package-url = 'https://github.com/Titouan-Gadeyne/pymodaq_plugins_alcatel'
description = 'some word about your plugin'

author = 'Titouan GADEYNE'
author-email = 'titouan.gadeyne@cea.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.0.0']
